version: '3.8'
services:
  server:
    container_name: 'go_stickers'
    ports:
      - '6969:42069'
    build:
      tags:
        - "go_stickers:latest"
    volumes:
      - .:/usr/src/app
    environment:
      DATABASE_URL: "host=db user=postgres password=postgres dbname=postgres sslmode=disable"
    command: go run cmd/main.go
    depends_on:
      - db
  db:
    image: postgres:alpine
    ports:
      - '5422:5423'
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: stickers
